### ISSUE TITLE
Upgrade library used in Sweepin SDK

### ISSUE THREAD

**Issue by GrayaMax** [Sweepin/SweepinConnect-android#1]
Hello,
can you upgrade libraries used in sweepin SDK to the last version please ?
(get some issues with the zxing library version used)

**Comment by WilliamMouline** [comment]
Hello GrayaMax, 
I'm currently working on it. I'm also adding a few useful features in the last version I will be releasing today.

**Comment by GrayaMax** [comment]
Everything looks great, thanks.
